// Normally generated by the FlutterFire CLI (`flutterfire configure`).
// This copy is hand-written, using the same Firebase web config already
// present in web/index.html (added earlier for Analytics) — so no extra
// console digging or CLI login is needed for Firestore/Auth to work too.
//
// These values are safe to commit — they identify the project, they are
// not secret keys. Real protection comes from firestore.rules.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show kIsWeb;

/// Whether real Firebase config is present. main.dart checks this before
/// calling Firebase.initializeApp so the rest of the site keeps working
/// (just without live chat) if this ever gets reset to a placeholder.
bool get firebaseIsConfigured =>
    DefaultFirebaseOptions.currentPlatform.apiKey != 'REPLACE_ME';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (!kIsWeb) {
      throw UnsupportedError(
        'This site is web-only; DefaultFirebaseOptions only supports web.',
      );
    }
    return web;
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWRgoB9Ge-3jj6TCryipUxMTAyLfxJWlQ',
    appId: '1:357297076336:web:4474d265296e3179f7dcb5',
    messagingSenderId: '357297076336',
    projectId: 'solarpvhk-96812',
    authDomain: 'solarpvhk-96812.firebaseapp.com',
    storageBucket: 'solarpvhk-96812.firebasestorage.app',
    measurementId: 'G-626BL1FT93',
  );
}
